trigger:
- main  # Trigger on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: nensiravaliya28/my-static-web-app  # Replace with your Docker Hub repo name
  tag: $(Build.BuildId)  # Unique tag for each build

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Image
    steps:
    - task: Checkout@v2
      displayName: Checkout Code

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: Dockerfile
        containerRegistry: DockerHubConnection
        repository: $(imageName)
        tags: $(tag)

    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        containerRegistry: DockerHubConnection
        repository: $(imageName)
        tags: $(tag)

- stage: Deploy
  displayName: Deploy to Azure Static Web App
  dependsOn: Build
  jobs:
  - job: DeployToAzure
    displayName: Deploy to Azure
    steps:
    - task: AzureCLI@2
      displayName: Deploy Static Web App
      inputs:
        azureSubscription: ''  # Replace with your Azure service connection name
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az staticwebapp update \
            --name "YourStaticWebAppName" \  # Replace with your Azure Static Web App name
            --source $(imageName):$(tag)
